require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ChapterLeadersController do

  # This should return the minimal set of attributes required to create a valid
  # ChapterLeader. As you add validations to ChapterLeader, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "chapter_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ChapterLeadersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all chapter_leaders as @chapter_leaders" do
      chapter_leader = ChapterLeader.create! valid_attributes
      get :index, {}, valid_session
      assigns(:chapter_leaders).should eq([chapter_leader])
    end
  end

  describe "GET show" do
    it "assigns the requested chapter_leader as @chapter_leader" do
      chapter_leader = ChapterLeader.create! valid_attributes
      get :show, {:id => chapter_leader.to_param}, valid_session
      assigns(:chapter_leader).should eq(chapter_leader)
    end
  end

  describe "GET new" do
    it "assigns a new chapter_leader as @chapter_leader" do
      get :new, {}, valid_session
      assigns(:chapter_leader).should be_a_new(ChapterLeader)
    end
  end

  describe "GET edit" do
    it "assigns the requested chapter_leader as @chapter_leader" do
      chapter_leader = ChapterLeader.create! valid_attributes
      get :edit, {:id => chapter_leader.to_param}, valid_session
      assigns(:chapter_leader).should eq(chapter_leader)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ChapterLeader" do
        expect {
          post :create, {:chapter_leader => valid_attributes}, valid_session
        }.to change(ChapterLeader, :count).by(1)
      end

      it "assigns a newly created chapter_leader as @chapter_leader" do
        post :create, {:chapter_leader => valid_attributes}, valid_session
        assigns(:chapter_leader).should be_a(ChapterLeader)
        assigns(:chapter_leader).should be_persisted
      end

      it "redirects to the created chapter_leader" do
        post :create, {:chapter_leader => valid_attributes}, valid_session
        response.should redirect_to(ChapterLeader.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved chapter_leader as @chapter_leader" do
        # Trigger the behavior that occurs when invalid params are submitted
        ChapterLeader.any_instance.stub(:save).and_return(false)
        post :create, {:chapter_leader => { "chapter_id" => "invalid value" }}, valid_session
        assigns(:chapter_leader).should be_a_new(ChapterLeader)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ChapterLeader.any_instance.stub(:save).and_return(false)
        post :create, {:chapter_leader => { "chapter_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested chapter_leader" do
        chapter_leader = ChapterLeader.create! valid_attributes
        # Assuming there are no other chapter_leaders in the database, this
        # specifies that the ChapterLeader created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ChapterLeader.any_instance.should_receive(:update_attributes).with({ "chapter_id" => "1" })
        put :update, {:id => chapter_leader.to_param, :chapter_leader => { "chapter_id" => "1" }}, valid_session
      end

      it "assigns the requested chapter_leader as @chapter_leader" do
        chapter_leader = ChapterLeader.create! valid_attributes
        put :update, {:id => chapter_leader.to_param, :chapter_leader => valid_attributes}, valid_session
        assigns(:chapter_leader).should eq(chapter_leader)
      end

      it "redirects to the chapter_leader" do
        chapter_leader = ChapterLeader.create! valid_attributes
        put :update, {:id => chapter_leader.to_param, :chapter_leader => valid_attributes}, valid_session
        response.should redirect_to(chapter_leader)
      end
    end

    describe "with invalid params" do
      it "assigns the chapter_leader as @chapter_leader" do
        chapter_leader = ChapterLeader.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ChapterLeader.any_instance.stub(:save).and_return(false)
        put :update, {:id => chapter_leader.to_param, :chapter_leader => { "chapter_id" => "invalid value" }}, valid_session
        assigns(:chapter_leader).should eq(chapter_leader)
      end

      it "re-renders the 'edit' template" do
        chapter_leader = ChapterLeader.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ChapterLeader.any_instance.stub(:save).and_return(false)
        put :update, {:id => chapter_leader.to_param, :chapter_leader => { "chapter_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested chapter_leader" do
      chapter_leader = ChapterLeader.create! valid_attributes
      expect {
        delete :destroy, {:id => chapter_leader.to_param}, valid_session
      }.to change(ChapterLeader, :count).by(-1)
    end

    it "redirects to the chapter_leaders list" do
      chapter_leader = ChapterLeader.create! valid_attributes
      delete :destroy, {:id => chapter_leader.to_param}, valid_session
      response.should redirect_to(chapter_leaders_url)
    end
  end

end
